### ISSUE TITLE
Error in the send_tx function

### ISSUE THREAD

**Issue by Revolutionnnn** [xian-network/xian-py#3]
When i try to make a trasaccion with the funtion send_tx i have this error
![image](https://github.com/user-attachments/assets/d9e61214-1c0e-4d29-9b87-ab24fd314f27)

when i deleted this code is ok
![image](https://github.com/user-attachments/assets/a01a0f15-d20f-46fc-8af0-0028aab70044)

**Comment by Endogen** [comment]
Yes that's because the current version of `xian-py` is already reworked to use the newest core codebase which isn't yet on mainnet. But you should be able to already use it on testnet.
